name: dagster
title: Dagster
icon: dagster

services:
  - name: dagster
    title: Dagster
    service: dagster
    links:
    - name: postgres
      service: postgres

  - name: postgres
    title: PostgreSQL
    service: postgres
